### ISSUE TITLE
"Invalid number of options" garbage text

### ISSUE THREAD

**Issue by TheRealDannyBoy** [ncmpcpp/ncmpcpp#353] opened 2019-10-01 21:31 UTC
**Describe the bug**
When playing certain music files, ncmpcpp prints a message "Invalid number of options" on the second line of the screen, which garbles up much of the other text on the screen.  It happens on both the alternative and classic layouts.

**To Reproduce**
1. Download [Talislanta: Wizard Hunter](https://www.drivethrurpg.com/product/210820/Talislanta-Wizard-Hunter) (I link this album because it is freely available and causes the issue.)
2. Unzip the archive into your mpd music library
3. Using ncmpcpp, locate the album and play it.
4. See "Invalid number of options" in the top left of your screen, on the second line.  Also look for (sometimes subtle) garbage on the rest of your screen.

**Expected behavior**
The "Invalid number of options" line not to show up and the text on my screen not to garble up.

**Screenshots/Logs**
error.log provided no information on the issue.
![2019-10-01_16-05-1](https://user-images.githubusercontent.com/45680053/66002123-950e8800-e468-11e9-980e-e154c535d6c5.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal: zsh on st (although the same bug has occurred on Alacritty and URXVT.)
 - Version 0.8.2

**Additional context**
I suspect it may have something to do with taglib.

**Comment by larson-carter** [comment] 2019-10-02 01:30
Hello, thank you for submitting an issue @TheRealDannyBoy can I do see where "Invalid number of options is there" but I do not see right off hand provided in the screenshot that you gave me the "garbage text" If you wouldn't mind to circle the so be garbage text to show me where it is in the screenshot due to me now seeing it right off hand. That way I can investigate better.

**Comment by TheRealDannyBoy** [comment] 2019-10-05 00:40
Perhaps "garbage text" was an imprecise term.  What I meant by it is that the "Invalid number of options" message seems to be pushing the text out of alignment.  I've circled a few examples.
![2019-10-01_16-05-1](https://user-images.githubusercontent.com/45680053/66247054-a19c1600-e6de-11e9-9f55-b0bd02f65cc3.png)

**Comment by adhirajsinghchauhan** [comment] 2019-10-05 18:06
@TheRealDannyBoy I see the problem. We'll investigate what causes this mis-render.

Have you noticed this bug with any other album?

**Comment by TheRealDannyBoy** [comment] 2019-10-05 22:20
Yes, several.  I'll get back to you with a more comprehensive list when I have some time on my hands.

**Comment by larson-carter** [comment] 2019-10-07 13:11
I do see the problem also. What is the language on your machine?

**Comment by larson-carter** [comment] 2019-10-23 19:12
@TheRealDannyBoy Ping

**Comment by TheRealDannyBoy** [comment] 2020-02-16 09:42
The default language on my machine is English.  I'm sorry that I never responded to your query; a complete bork of my system, followed by a real-life crisis that prevented me from fixing said bork, took my focus off of this and I totally forgot that I'd opened it.  I have since wiped my machine and installed openSUSE Tumbleweed on it, where I am no longer experiencing the issue.  Again, I am sorry for my inexcusably long hiatus and will be happy to answer any questions I can.

**Comment by DuckDuckQuak** [comment] 2020-10-24 14:49
Hi all, I think I've found the cause of this.

It seems the output of execute_on_song_change in the config is being printed at the start of the second line somehow.

For example when `execute_on_song_change = printf test` the following happens
![2020-10-24-152243_1920x1080_scrot](https://user-images.githubusercontent.com/46086195/97084182-ae025200-1604-11eb-98a4-807f8be7a4c3.png)

"Invalid number of options." is just the output from using notify-send with too many arguments.
`execute_on_song_change = notify-send arg1 arg2 arg3`
![2020-10-24-152756_1920x1080_scrot](https://user-images.githubusercontent.com/46086195/97084241-44367800-1605-11eb-99e6-50c509f56d37.png)

If there's no output from execute_on_song_change then the issue doesn't happen.

**Comment by arybczak** [comment] 2020-12-21 18:51
Fixed in f3fe45f3ff6f12edcba501d074fa0e45bfada7ef.

**Closed by arybczak** 2020-12-21 18:51 UTC
Labels: bug
