### ISSUE TITLE
[BUG] Genius endpoint doesn't return lyrics

### ISSUE THREAD

**Issue by ghost** [ncmpcpp/ncmpcpp#572] opened 2023-05-14 14:10 UTC
**Describe the bug**
Genius lyrics do not seem to return lyrics, but instead the guide for contributing to Genius.

**To Reproduce**
1. Using Arch, enter ncmpcpp and play a song that is confirmed to have full lyrics on Genius
2. Press 'l' to obtain the lyrics

**Expected behavior**
The lyrics from Genius

**Screenshots/Logs**
![image](https://github.com/ncmpcpp/ncmpcpp/assets/108785622/b590ac36-4156-4a1c-bf13-f0019fb903d4)

**Desktop (please complete the following information):**
 - OS: Arch
 - Terminal: zsh
 - Version 0.9.2-10

**Additional context**
I listen to Japanese-language songs, and sometimes it seems to be trying to use an English translation or a romanization, which may or may not exist

**Comment by bpampel** [comment] 2023-08-11 11:53
This is likely a duplicate of https://github.com/ncmpcpp/ncmpcpp/issues/566

The genius fetcher was already fixed 2 years ago: https://github.com/ncmpcpp/ncmpcpp/commit/df1c4d7d7dee601a580169873ddb675d773777a5
 Works fine for me when compiling from the master branch, but there wasn't a release since.

**Comment by arybczak** [comment] 2024-07-24 18:37
It works in master.

**Closed by arybczak** 2024-07-24 18:37 UTC
Labels: bug
